# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Software_Bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_export_file(object):
    def setupUi(self, export_file):
        export_file.setObjectName("export_file")
        export_file.resize(579, 490)
        self.horizontalLayoutWidget = QtWidgets.QWidget(export_file)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 360, 551, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.opencam = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.opencam.setObjectName("opencam")
        self.horizontalLayout.addWidget(self.opencam)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.closecam = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.closecam.setObjectName("closecam")
        self.horizontalLayout.addWidget(self.closecam)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.Stream_video = QtWidgets.QLabel(export_file)
        self.Stream_video.setGeometry(QtCore.QRect(30, 10, 521, 321))
        self.Stream_video.setAutoFillBackground(False)
        self.Stream_video.setObjectName("Stream_video")
        self.label_Bar = QtWidgets.QLabel(export_file)
        self.label_Bar.setGeometry(QtCore.QRect(20, 400, 531, 81))
        self.label_Bar.setObjectName("label_Bar")

        self.retranslateUi(export_file)
        QtCore.QMetaObject.connectSlotsByName(export_file)

    def retranslateUi(self, export_file):
        _translate = QtCore.QCoreApplication.translate
        export_file.setWindowTitle(_translate("export_file", "Form"))
        self.opencam.setText(_translate("export_file", "Open camera"))
        self.closecam.setText(_translate("export_file", "Close camera"))
        self.pushButton.setText(_translate("export_file", "Export file"))
        self.Stream_video.setText(_translate("export_file", "TextLabel"))
        self.label_Bar.setText(_translate("export_file", "TextLabel"))



